from typing import Any

class constexpr(int):
    ...

def arange(*args: Any, **kwargs: Any) -> Any: ...
def program_id(axis: int) -> Any: ...
def load(ptr: Any, mask: Any = ..., other: Any = ...) -> Any: ...
def store(ptr: Any, value: Any, mask: Any = ...) -> None: ...
def exp(x: Any) -> Any: ...
def where(cond: Any, a: Any, b: Any) -> Any: ...

float32: Any
